services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - /backend/__pycache__
      - /backend/.venv
