FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

ENV POETRY_HOME="/opt/poetry"
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_NO_INTERACTION=1

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /opt/poetry/bin/poetry /usr/local/bin/poetry

WORKDIR /backend

COPY pyproject.toml ./
COPY poetry.lock ./

RUN poetry lock

RUN poetry config virtualenvs.in-project true

RUN poetry install --no-root

RUN poetry add uvicorn

RUN poetry env activate

ENV PORT=8000
ENV PYTHONPATH=/backend

EXPOSE 8000

CMD [ "poetry", "run", "uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]