FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y curl build-essential && rm -rf /var/lib/apt/lists/*

ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"
ENV PYTHONPATH=/backend

RUN curl -sSL https://install.python-poetry.org | python3 -

RUN poetry config virtualenvs.create false

WORKDIR /backend

COPY pyproject.toml poetry.lock* ./

RUN poetry install --no-interaction --no-ansi --with dev --no-root

COPY . .

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
